export const MASTER_WORDS = [
  { id: 1, english: "ability", hebrew: "יכולת", partOfSpeech: "noun" },
  { id: 2, english: "able to", hebrew: "מסוגל ל-, יכול ל-", partOfSpeech: "verb" },
  { id: 3, english: "about", hebrew: "על אודות, לגבי", partOfSpeech: "preposition" },
  { id: 4, english: "above", hebrew: "מעל, למעלה", partOfSpeech: "adjective" },
  { id: 5, english: "academy", hebrew: "אקדמיה", partOfSpeech: "noun" },
  { id: 6, english: "access", hebrew: "גישה, לגשת", partOfSpeech: "noun, verb" },
  { id: 7, english: "accident", hebrew: "תאונה", partOfSpeech: "noun" },
  { id: 8, english: "according to", hebrew: "על פי, לפי", partOfSpeech: "preposition" },
  { id: 9, english: "account", hebrew: "חשבון", partOfSpeech: "noun" },
  { id: 10, english: "achieve", hebrew: "להשיג, להגשים", partOfSpeech: "verb" },
  { id: 11, english: "achievement", hebrew: "הישג", partOfSpeech: "noun" },
  { id: 12, english: "activate", hebrew: "להפעיל", partOfSpeech: "verb" },
  { id: 13, english: "active", hebrew: "פעיל", partOfSpeech: "adjective" },
  { id: 14, english: "activity", hebrew: "פעילות", partOfSpeech: "noun" },
  { id: 15, english: "advantage", hebrew: "יתרון", partOfSpeech: "noun" },
  { id: 16, english: "advertisement", hebrew: "פרסומת", partOfSpeech: "noun" },
  { id: 17, english: "advice", hebrew: "עצה, ייעוץ", partOfSpeech: "noun" },
  { id: 18, english: "affect", hebrew: "להשפיע על", partOfSpeech: "verb" },
  { id: 19, english: "afford", hebrew: "להרשות לעצמו", partOfSpeech: "verb" },
  { id: 20, english: "after", hebrew: "אחרי, לאחר", partOfSpeech: "preposition" },
  { id: 21, english: "afternoon", hebrew: "אחר הצהריים", partOfSpeech: "noun" },
  { id: 22, english: "aim", hebrew: "לכוון, כוונה", partOfSpeech: "noun, verb" },
  { id: 23, english: "air", hebrew: "אוויר", partOfSpeech: "noun" },
  { id: 24, english: "airport", hebrew: "שדה תעופה", partOfSpeech: "noun" },
  { id: 25, english: "all over the world", hebrew: "בכל רחבי העולם", partOfSpeech: "idiom" },
  { id: 26, english: "allow", hebrew: "לאפשר, להתיר", partOfSpeech: "verb" },
  { id: 27, english: "also", hebrew: "גם, כמו כן", partOfSpeech: "adverb" },
  { id: 28, english: "although", hebrew: "למרות ש-, אף על פי ש-", partOfSpeech: "conjunction" },
  { id: 29, english: "always", hebrew: "תמיד", partOfSpeech: "adverb" },
  { id: 30, english: "amount", hebrew: "כמות", partOfSpeech: "noun" },
  { id: 31, english: "and", hebrew: "ו-, וגם", partOfSpeech: "conjunction" },
  { id: 32, english: "angry", hebrew: "כועס", partOfSpeech: "adjective" },
  { id: 33, english: "answer", hebrew: "תשובה, לענות", partOfSpeech: "noun, verb" },
  { id: 34, english: "anything", hebrew: "כל דבר, משהו", partOfSpeech: "pronoun" },
  { id: 35, english: "appear", hebrew: "להופיע", partOfSpeech: "verb" },
  { id: 36, english: "appliances", hebrew: "מכשירי חשמל (ביתיים)", partOfSpeech: "noun (plural)" },
  { id: 37, english: "area", hebrew: "אזור, שטח", partOfSpeech: "noun" },
  { id: 38, english: "army", hebrew: "צבא", partOfSpeech: "noun" },
  { id: 39, english: "around the world", hebrew: "מסביב לעולם", partOfSpeech: "collocation" },
  { id: 40, english: "arrive", hebrew: "להגיע", partOfSpeech: "verb" },
  { id: 41, english: "article", hebrew: "מאמר, כתבה", partOfSpeech: "noun" },
  { id: 42, english: "as a result", hebrew: "כתוצאה מ-", partOfSpeech: "idiom" },
  { id: 43, english: "attachment", hebrew: "קובץ מצורף", partOfSpeech: "noun" },
  { id: 44, english: "aunt", hebrew: "דודה", partOfSpeech: "noun" },
  { id: 45, english: "author", hebrew: "מחבר, סופר", partOfSpeech: "noun" },
  { id: 46, english: "autumn", hebrew: "סתיו", partOfSpeech: "noun" },
  { id: 47, english: "average", hebrew: "ממוצע", partOfSpeech: "noun" },
  { id: 48, english: "avoid", hebrew: "להימנע מ-", partOfSpeech: "verb" },
  { id: 49, english: "bad", hebrew: "רע", partOfSpeech: "adjective" },
  { id: 50, english: "bag", hebrew: "תיק, שקית", partOfSpeech: "noun" },
  { id: 51, english: "balance", hebrew: "איזון, יתרה", partOfSpeech: "noun" },
  { id: 52, english: "battery", hebrew: "סוללה", partOfSpeech: "noun" },
  { id: 53, english: "because", hebrew: "כי, משום ש-", partOfSpeech: "conjunction" },
  { id: 54, english: "become", hebrew: "להפוך ל-, להיות", partOfSpeech: "verb" },
  { id: 55, english: "before", hebrew: "לפני", partOfSpeech: "preposition" },
  { id: 56, english: "begin", hebrew: "להתחיל", partOfSpeech: "verb" },
  { id: 57, english: "behavior", hebrew: "התנהגות", partOfSpeech: "noun" },
  { id: 58, english: "behind", hebrew: "מאחורי", partOfSpeech: "preposition" },
  { id: 59, english: "belief", hebrew: "אמונה", partOfSpeech: "noun" },
  { id: 60, english: "believe", hebrew: "להאמין", partOfSpeech: "verb" },
  { id: 61, english: "belong", hebrew: "להשתייך ל-", partOfSpeech: "verb" },
  { id: 62, english: "below", hebrew: "למטה, מתחת", partOfSpeech: "adverb" },
  { id: 63, english: "benefit", hebrew: "תועלת, להועיל", partOfSpeech: "noun, verb" },
  { id: 64, english: "better", hebrew: "יותר טוב", partOfSpeech: "adjective" },
  { id: 65, english: "between", hebrew: "בין", partOfSpeech: "preposition" },
  { id: 66, english: "bicycle", hebrew: "אופניים", partOfSpeech: "noun" },
  { id: 67, english: "big", hebrew: "גדול", partOfSpeech: "adjective" },
  { id: 68, english: "blood", hebrew: "דם", partOfSpeech: "noun" },
  { id: 69, english: "blow", hebrew: "לנשוב, לנפח", partOfSpeech: "verb" },
  { id: 70, english: "book", hebrew: "ספר, לשריין (מקום)", partOfSpeech: "noun, verb" },
  { id: 71, english: "both", hebrew: "שניהם, גם וגם", partOfSpeech: "determiner" },
  { id: 72, english: "break", hebrew: "לשבור, הפסקה", partOfSpeech: "verb, noun" },
  { id: 73, english: "break a record", hebrew: "לשבור שיא", partOfSpeech: "collocation" },
  { id: 74, english: "breakfast", hebrew: "ארוחת בוקר", partOfSpeech: "noun" },
  { id: 75, english: "bring", hebrew: "להביא", partOfSpeech: "verb" },
  { id: 76, english: "brother", hebrew: "אח", partOfSpeech: "noun" },
  { id: 77, english: "brush", hebrew: "מברשת, לצחצח", partOfSpeech: "verb, noun" },
  { id: 78, english: "build", hebrew: "לבנות", partOfSpeech: "verb" },
  { id: 79, english: "building", hebrew: "בניין", partOfSpeech: "noun" },
  { id: 80, english: "bus", hebrew: "אוטובוס", partOfSpeech: "noun" },
  { id: 81, english: "business", hebrew: "עסק", partOfSpeech: "noun" },
  { id: 82, english: "busy", hebrew: "עסוק", partOfSpeech: "adjective" },
  { id: 83, english: "but", hebrew: "אבל", partOfSpeech: "conjunction" },
  { id: 84, english: "button", hebrew: "כפתור", partOfSpeech: "noun" },
  { id: 85, english: "buy", hebrew: "לקנות", partOfSpeech: "verb" },
  { id: 86, english: "calendar", hebrew: "לוח שנה", partOfSpeech: "noun" },
  { id: 87, english: "call", hebrew: "לקרוא, לטלפן", partOfSpeech: "verb" },
  { id: 88, english: "camera", hebrew: "מצלמה", partOfSpeech: "noun" },
  { id: 89, english: "can", hebrew: "יכול, מסוגל", partOfSpeech: "verb" },
  { id: 90, english: "capacity", hebrew: "קיבולת, יכולת", partOfSpeech: "noun" },
  { id: 91, english: "car", hebrew: "מכונית", partOfSpeech: "noun" },
  { id: 92, english: "career", hebrew: "קריירה, מקצוע", partOfSpeech: "noun" },
  { id: 93, english: "careful", hebrew: "זהיר", partOfSpeech: "adjective" },
  { id: 94, english: "carry", hebrew: "לשאת, לסחוב", partOfSpeech: "verb" },
  { id: 95, english: "catch", hebrew: "לתפוס", partOfSpeech: "verb" },
  { id: 96, english: "cause", hebrew: "גורם, לגרום", partOfSpeech: "verb, noun" },
  { id: 97, english: "cell phone", hebrew: "טלפון סלולרי", partOfSpeech: "noun" },
  { id: 98, english: "celsius", hebrew: "צלזיוס", partOfSpeech: "adjective" },
  { id: 99, english: "center", hebrew: "מרכז", partOfSpeech: "noun" },
  { id: 100, english: "centimeter", hebrew: "סנטימטר", partOfSpeech: "noun" },
  { id: 101, english: "century", hebrew: "מאה (שנים)", partOfSpeech: "noun" },
  { id: 102, english: "certain", hebrew: "בטוח, מסוים", partOfSpeech: "adjective" },
  { id: 103, english: "chair", hebrew: "כסא", partOfSpeech: "noun" },
  { id: 104, english: "challenge", hebrew: "אתגר, לאתגר", partOfSpeech: "noun, verb" },
  { id: 105, english: "change", hebrew: "שינוי, לשנות", partOfSpeech: "noun, verb" },
  { id: 106, english: "channel", hebrew: "ערוץ", partOfSpeech: "noun" },
  { id: 107, english: "charge", hebrew: "להטעין, לחייב", partOfSpeech: "verb" },
  { id: 108, english: "charger", hebrew: "מטען", partOfSpeech: "noun" },
  { id: 109, english: "chart", hebrew: "תרשים, גרף", partOfSpeech: "noun" },
  { id: 110, english: "cheap", hebrew: "זול", partOfSpeech: "adjective" },
  { id: 111, english: "check", hebrew: "לבדוק, בדיקה, המחאה", partOfSpeech: "verb, noun" },
  { id: 112, english: "child", hebrew: "ילד/ה", partOfSpeech: "noun (singular)" },
  { id: 113, english: "children", hebrew: "ילדים", partOfSpeech: "noun (plural)" },
  { id: 114, english: "choice", hebrew: "בחירה", partOfSpeech: "noun" },
  { id: 115, english: "choose", hebrew: "לבחור", partOfSpeech: "verb" },
  { id: 116, english: "circle", hebrew: "עיגול, להקיף", partOfSpeech: "noun, verb" },
  { id: 117, english: "circular", hebrew: "עגול, מעגלי", partOfSpeech: "adjective" },
  { id: 118, english: "city", hebrew: "עיר", partOfSpeech: "noun" },
  { id: 119, english: "clean", hebrew: "נקי, לנקות", partOfSpeech: "adjective, verb" },
  { id: 120, english: "climate", hebrew: "אקלים", partOfSpeech: "noun" },
  { id: 121, english: "close", hebrew: "לסגור, קרוב", partOfSpeech: "verb, adjective" },
  { id: 122, english: "cold", hebrew: "קר", partOfSpeech: "adjective" },
  { id: 123, english: "collect", hebrew: "לאסוף, לאגור", partOfSpeech: "verb" },
  { id: 124, english: "college", hebrew: "מכללה", partOfSpeech: "noun" },
  { id: 125, english: "come", hebrew: "לבוא", partOfSpeech: "verb" },
  { id: 126, english: "common", hebrew: "נפוץ, משותף", partOfSpeech: "adjective" },
  { id: 127, english: "communicate", hebrew: "לתקשר", partOfSpeech: "verb" },
  { id: 128, english: "communication", hebrew: "תקשורת", partOfSpeech: "noun" },
  { id: 129, english: "community", hebrew: "קהילה", partOfSpeech: "noun" },
  { id: 130, english: "company", hebrew: "חברה (עסקית)", partOfSpeech: "noun" },
  { id: 131, english: "compare", hebrew: "להשוות", partOfSpeech: "verb" },
  { id: 132, english: "competition", hebrew: "תחרות", partOfSpeech: "noun" },
  { id: 133, english: "complete", hebrew: "מלא, להשלים", partOfSpeech: "verb, adjective" },
  { id: 134, english: "computer", hebrew: "מחשב", partOfSpeech: "noun" },
  { id: 135, english: "conclusion", hebrew: "מסקנה", partOfSpeech: "noun" },
  { id: 136, english: "concrete", hebrew: "בטון, מוחשי", partOfSpeech: "noun, adjective" },
  { id: 137, english: "condition", hebrew: "מצב, תנאי", partOfSpeech: "noun" },
  { id: 138, english: "connect", hebrew: "לחבר", partOfSpeech: "verb" },
  { id: 139, english: "connection", hebrew: "חיבור, קשר", partOfSpeech: "noun" },
  { id: 140, english: "construct", hebrew: "להקים, להרכיב (מבנה)", partOfSpeech: "verb" },
  { id: 141, english: "consume", hebrew: "לצרוך", partOfSpeech: "verb" },
  { id: 142, english: "consumer", hebrew: "צרכן", partOfSpeech: "noun" },
  { id: 143, english: "continue", hebrew: "להמשיך", partOfSpeech: "verb" },
  { id: 144, english: "control", hebrew: "שליטה, בקרה", partOfSpeech: "verb, noun" },
  { id: 145, english: "copy", hebrew: "העתק, להעתיק", partOfSpeech: "verb, noun" },
  { id: 146, english: "cost", hebrew: "עלות, לעלות", partOfSpeech: "verb, noun" },
  { id: 147, english: "country", hebrew: "מדינה", partOfSpeech: "noun" },
  { id: 148, english: "cousin", hebrew: "בן/בת דוד", partOfSpeech: "noun" },
  { id: 149, english: "crash", hebrew: "התרסקות, להתרסק", partOfSpeech: "noun, verb" },
  { id: 150, english: "create", hebrew: "ליצור", partOfSpeech: "verb" },
  { id: 151, english: "customer", hebrew: "לקוח", partOfSpeech: "noun" },
  { id: 152, english: "damage", hebrew: "נזק", partOfSpeech: "noun" },
  { id: 153, english: "danger", hebrew: "סכנה", partOfSpeech: "noun" },
  { id: 154, english: "dangerous", hebrew: "מסוכן", partOfSpeech: "adjective" },
  { id: 155, english: "data", hebrew: "נתונים, מידע", partOfSpeech: "noun" },
  { id: 156, english: "daughter", hebrew: "בת", partOfSpeech: "noun" },
  { id: 157, english: "day", hebrew: "יום", partOfSpeech: "noun" },
  { id: 158, english: "decade", hebrew: "עשור", partOfSpeech: "noun" },
  { id: 159, english: "decide", hebrew: "להחליט", partOfSpeech: "verb" },
  { id: 160, english: "decision", hebrew: "החלטה", partOfSpeech: "noun" },
  { id: 161, english: "decrease", hebrew: "להפחית, צמצום, ירידה", partOfSpeech: "verb, noun" },
  { id: 162, english: "depend on", hebrew: "תלוי ב-", partOfSpeech: "phrasal verb" },
  { id: 163, english: "describe", hebrew: "לתאר", partOfSpeech: "verb" },
  { id: 164, english: "description", hebrew: "תיאור", partOfSpeech: "noun" },
  { id: 165, english: "design", hebrew: "עיצוב, לעצב", partOfSpeech: "noun, verb" },
  { id: 166, english: "desk", hebrew: "שולחן (כתיבה)", partOfSpeech: "noun" },
  { id: 167, english: "destroy", hebrew: "להרוס", partOfSpeech: "verb" },
  { id: 168, english: "develop", hebrew: "לפתח", partOfSpeech: "verb" },
  { id: 169, english: "device", hebrew: "מכשיר, התקן", partOfSpeech: "noun" },
  { id: 170, english: "difference", hebrew: "הבדל", partOfSpeech: "noun" },
  { id: 171, english: "different", hebrew: "שונה", partOfSpeech: "adjective" },
  { id: 172, english: "difficult", hebrew: "קשה, מורכב", partOfSpeech: "adjective" },
  { id: 173, english: "dinner", hebrew: "ארוחת ערב", partOfSpeech: "noun" },
  { id: 174, english: "direction", hebrew: "כיוון", partOfSpeech: "noun" },
  { id: 175, english: "dirt", hebrew: "לכלוך", partOfSpeech: "noun" },
  { id: 176, english: "disable", hebrew: "לנטרל, להשבית, לבטל", partOfSpeech: "verb" },
  { id: 177, english: "disadvantage", hebrew: "חיסרון", partOfSpeech: "noun" },
  { id: 178, english: "disappear", hebrew: "להיעלם", partOfSpeech: "verb" },
  { id: 179, english: "discover", hebrew: "לגלות (תגלית / משהו חדש)", partOfSpeech: "verb" },
  { id: 180, english: "disease", hebrew: "מחלה", partOfSpeech: "noun" },
  { id: 181, english: "distance learning", hebrew: "למידה מרחוק", partOfSpeech: "noun" },
  { id: 182, english: "do", hebrew: "לעשות", partOfSpeech: "verb" },
  { id: 183, english: "download", hebrew: "להוריד (קובץ)", partOfSpeech: "verb" },
  { id: 184, english: "draw", hebrew: "לצייר, לשרטט", partOfSpeech: "verb" },
  { id: 185, english: "drink", hebrew: "משקה, לשתות", partOfSpeech: "verb, noun" },
  { id: 186, english: "drive", hebrew: "לנהוג, כונן", partOfSpeech: "verb, noun" },
  { id: 187, english: "driver", hebrew: "נהג", partOfSpeech: "noun" },
  { id: 188, english: "drone", hebrew: "רחפן", partOfSpeech: "noun" },
  { id: 189, english: "dry", hebrew: "יבש", partOfSpeech: "adjective" },
  { id: 190, english: "during", hebrew: "במהלך, תוך כדי", partOfSpeech: "preposition" },
  { id: 191, english: "dust", hebrew: "אבק, לנגב אבק", partOfSpeech: "noun, verb" },
  { id: 192, english: "early", hebrew: "מוקדם", partOfSpeech: "adjective" },
  { id: 193, english: "earthquake", hebrew: "רעידת אדמה", partOfSpeech: "noun" },
  { id: 194, english: "easy", hebrew: "קל", partOfSpeech: "adjective" },
  { id: 195, english: "eat", hebrew: "לאכול", partOfSpeech: "verb" },
  { id: 196, english: "education", hebrew: "חינוך, השכלה", partOfSpeech: "noun" },
  { id: 197, english: "effect", hebrew: "השפעה, תוצאה", partOfSpeech: "noun" },
  { id: 198, english: "effective", hebrew: "אפקטיבי, מועיל", partOfSpeech: "adjective" },
  { id: 199, english: "efficient", hebrew: "יעיל", partOfSpeech: "adjective" },
  { id: 200, english: "electricity", hebrew: "חשמל", partOfSpeech: "noun" },
  { id: 201, english: "electronic", hebrew: "אלקטרוני", partOfSpeech: "adjective" },
  { id: 202, english: "employ", hebrew: "להעסיק", partOfSpeech: "verb" },
  { id: 203, english: "employee", hebrew: "עובד", partOfSpeech: "noun" },
  { id: 204, english: "employer", hebrew: "מעסיק", partOfSpeech: "noun" },
  { id: 205, english: "employment", hebrew: "תעסוקה", partOfSpeech: "noun" },
  { id: 206, english: "enable", hebrew: "לאפשר", partOfSpeech: "verb" },
  { id: 207, english: "encourage", hebrew: "לעודד", partOfSpeech: "verb" },
  { id: 208, english: "end", hebrew: "סוף, לסיים", partOfSpeech: "noun, verb" },
  { id: 209, english: "energy", hebrew: "אנרגיה", partOfSpeech: "noun" },
  { id: 210, english: "engine", hebrew: "מנוע", partOfSpeech: "noun" },
  { id: 211, english: "engineer", hebrew: "מהנדס", partOfSpeech: "noun" },
  { id: 212, english: "enough", hebrew: "מספיק", partOfSpeech: "determiner" },
  { id: 213, english: "enter", hebrew: "להיכנס", partOfSpeech: "verb" },
  { id: 214, english: "entire", hebrew: "שלם, כולו", partOfSpeech: "adjective" },
  { id: 215, english: "environment", hebrew: "סביבה", partOfSpeech: "noun" },
  { id: 216, english: "equipment", hebrew: "ציוד", partOfSpeech: "noun" },
  { id: 217, english: "escape", hebrew: "לברוח, להימלט", partOfSpeech: "verb" },
  { id: 218, english: "evening", hebrew: "ערב", partOfSpeech: "noun" },
  { id: 219, english: "everyone", hebrew: "כולם", partOfSpeech: "pronoun" },
  { id: 220, english: "everything", hebrew: "הכל", partOfSpeech: "pronoun" },
  { id: 221, english: "exercise", hebrew: "תרגיל, להתאמן", partOfSpeech: "verb, noun" },
  { id: 222, english: "exist", hebrew: "להתקיים, לקיים", partOfSpeech: "verb" },
  { id: 223, english: "expensive", hebrew: "יקר", partOfSpeech: "adjective" },
  { id: 224, english: "experience", hebrew: "ניסיון, לחוות", partOfSpeech: "noun, verb" },
  { id: 225, english: "experiment", hebrew: "ניסוי", partOfSpeech: "noun" },
  { id: 226, english: "expert", hebrew: "מומחה", partOfSpeech: "noun" },
  { id: 227, english: "explain", hebrew: "להסביר", partOfSpeech: "verb" },
  { id: 228, english: "exterior", hebrew: "חיצוני", partOfSpeech: "adjective" },
  { id: 229, english: "fact", hebrew: "עובדה", partOfSpeech: "noun" },
  { id: 230, english: "factor", hebrew: "גורם", partOfSpeech: "noun" },
  { id: 231, english: "factory", hebrew: "מפעל", partOfSpeech: "noun" },
  { id: 232, english: "fall", hebrew: "סתיו, ליפול", partOfSpeech: "noun, verb" },
  { id: 233, english: "family", hebrew: "משפחה", partOfSpeech: "noun" },
  { id: 234, english: "famous", hebrew: "מפורסם", partOfSpeech: "adjective" },
  { id: 235, english: "far", hebrew: "רחוק", partOfSpeech: "adjective" },
  { id: 236, english: "fast", hebrew: "מהיר, מהר", partOfSpeech: "adjective" },
  { id: 237, english: "father", hebrew: "אב, אבא", partOfSpeech: "noun" },
  { id: 238, english: "favorite", hebrew: "מועדף", partOfSpeech: "adjective" },
  { id: 239, english: "feature", hebrew: "תכונה, מאפיין", partOfSpeech: "noun" },
  { id: 240, english: "finally", hebrew: "לבסוף", partOfSpeech: "adverb" },
  { id: 241, english: "find", hebrew: "למצוא", partOfSpeech: "verb" },
  { id: 242, english: "find out", hebrew: "לברר, לגלות (מידע)", partOfSpeech: "verb" },
  { id: 243, english: "first", hebrew: "ראשון", partOfSpeech: "adjective" },
  { id: 244, english: "fix", hebrew: "לתקן", partOfSpeech: "verb" },
  { id: 245, english: "flight", hebrew: "טיסה", partOfSpeech: "noun" },
  { id: 246, english: "fly", hebrew: "לעוף", partOfSpeech: "verb" },
  { id: 247, english: "for example", hebrew: "לדוגמה", partOfSpeech: "adverb" },
  { id: 248, english: "force", hebrew: "כוח, לכפות", partOfSpeech: "noun, verb" },
  { id: 249, english: "forget", hebrew: "לשכוח", partOfSpeech: "verb" },
  { id: 250, english: "frequently", hebrew: "לעתים קרובות", partOfSpeech: "adverb" },
  { id: 251, english: "friend", hebrew: "חבר", partOfSpeech: "noun" },
  { id: 252, english: "fuel", hebrew: "דלק", partOfSpeech: "noun" },
  { id: 253, english: "fun", hebrew: "כיף, מהנה", partOfSpeech: "adjective" },
  { id: 254, english: "function", hebrew: "פונקציה, לתפקד", partOfSpeech: "noun, verb" },
  { id: 255, english: "future", hebrew: "עתיד", partOfSpeech: "noun" },
  { id: 256, english: "garage", hebrew: "מוסך", partOfSpeech: "noun" },
  { id: 257, english: "garden", hebrew: "גינה", partOfSpeech: "noun" },
  { id: 258, english: "generous", hebrew: "נדיב", partOfSpeech: "adjective" },
  { id: 259, english: "get", hebrew: "לקבל, להשיג", partOfSpeech: "verb" },
  { id: 260, english: "get rid of", hebrew: "להיפטר מ-", partOfSpeech: "idiom" },
  { id: 261, english: "gift", hebrew: "מתנה", partOfSpeech: "noun" },
  { id: 262, english: "glass", hebrew: "זכוכית, כוס", partOfSpeech: "noun" },
  { id: 263, english: "go", hebrew: "ללכת", partOfSpeech: "verb" },
  { id: 264, english: "goal", hebrew: "מטרה, שער, יעד", partOfSpeech: "noun" },
  { id: 265, english: "good", hebrew: "טוב", partOfSpeech: "adjective" },
  { id: 266, english: "grandfather", hebrew: "סבא", partOfSpeech: "noun" },
  { id: 267, english: "grandmother", hebrew: "סבתא", partOfSpeech: "noun" },
  { id: 268, english: "gravity", hebrew: "כוח משיכה", partOfSpeech: "noun" },
  { id: 269, english: "ground", hebrew: "אדמה, קרקע, לטחון", partOfSpeech: "noun, verb" },
  { id: 270, english: "habit", hebrew: "הרגל", partOfSpeech: "noun" },
  { id: 271, english: "handle", hebrew: "ידית, לטפל", partOfSpeech: "noun, verb" },
  { id: 272, english: "hang", hebrew: "לתלות", partOfSpeech: "verb" },
  { id: 273, english: "hard", hebrew: "קשה, קשיח", partOfSpeech: "adjective" },
  { id: 274, english: "hardware", hebrew: "חומרה", partOfSpeech: "noun" },
  { id: 275, english: "harmful", hebrew: "מזיק", partOfSpeech: "adjective" },
  { id: 276, english: "harmless", hebrew: "לא מזיק", partOfSpeech: "adjective" },
  { id: 277, english: "hate", hebrew: "לשנוא", partOfSpeech: "verb" },
  { id: 278, english: "healthy", hebrew: "בריא", partOfSpeech: "adjective" },
  { id: 279, english: "hear", hebrew: "לשמוע", partOfSpeech: "verb" },
  { id: 280, english: "heat", hebrew: "חום, לחמם", partOfSpeech: "verb" },
  { id: 281, english: "heavy", hebrew: "כבד", partOfSpeech: "adjective" },
  { id: 282, english: "height", hebrew: "גובה", partOfSpeech: "noun" },
  { id: 283, english: "help", hebrew: "עזרה, לעזור", partOfSpeech: "verb" },
  { id: 284, english: "high", hebrew: "גבוה", partOfSpeech: "adjective" },
  { id: 285, english: "high tech", hebrew: "טכנולוגיה עילית", partOfSpeech: "noun" },
  { id: 286, english: "hobby", hebrew: "תחביב", partOfSpeech: "noun" },
  { id: 287, english: "hospital", hebrew: "בית חולים", partOfSpeech: "noun" },
  { id: 288, english: "hot", hebrew: "חם", partOfSpeech: "adjective" },
  { id: 289, english: "hotel", hebrew: "בית מלון", partOfSpeech: "noun" },
  { id: 290, english: "house", hebrew: "בית", partOfSpeech: "noun" },
  { id: 291, english: "how", hebrew: "איך", partOfSpeech: "interrogation" },
  { id: 292, english: "how long", hebrew: "כמה זמן", partOfSpeech: "interrogation" },
  { id: 293, english: "how many", hebrew: "כמה (ספירה)", partOfSpeech: "interrogation" },
  { id: 294, english: "how much", hebrew: "כמה (כמות)", partOfSpeech: "interrogation" },
  { id: 295, english: "how often", hebrew: "באיזו תדירות", partOfSpeech: "interrogation" },
  { id: 296, english: "however", hebrew: "עם זאת, אולם", partOfSpeech: "adverb" },
  { id: 297, english: "hungry", hebrew: "רעב", partOfSpeech: "adjective" },
  { id: 298, english: "husband", hebrew: "בעל, בן זוג", partOfSpeech: "noun" },
  { id: 299, english: "idea", hebrew: "רעיון", partOfSpeech: "noun" },
  { id: 300, english: "imagine", hebrew: "לדמיין", partOfSpeech: "verb" },
  { id: 301, english: "important", hebrew: "חשוב", partOfSpeech: "adjective" },
  { id: 302, english: "improve", hebrew: "לשפר", partOfSpeech: "verb" },
  { id: 303, english: "in", hebrew: "ב-, בתוך", partOfSpeech: "preposition" },
  { id: 304, english: "in addition", hebrew: "בנוסף", partOfSpeech: "idiom" },
  { id: 305, english: "in common", hebrew: "במשותף", partOfSpeech: "adverb" },
  { id: 306, english: "in conclusion", hebrew: "לסיכום", partOfSpeech: "idiom" },
  { id: 307, english: "in order to", hebrew: "כדי ל-, על מנת ל-", partOfSpeech: "conjunction" },
  { id: 308, english: "income", hebrew: "הכנסה", partOfSpeech: "noun" },
  { id: 309, english: "increase", hebrew: "עלייה, להגדיל, להעלות", partOfSpeech: "verb, noun" },
  { id: 310, english: "indoor", hebrew: "פנימי", partOfSpeech: "adjective" },
  { id: 311, english: "influence", hebrew: "השפעה, להשפיע", partOfSpeech: "noun, verb" },
  { id: 312, english: "information", hebrew: "מידע", partOfSpeech: "noun" },
  { id: 313, english: "injury", hebrew: "פציעה", partOfSpeech: "noun" },
  { id: 314, english: "inside", hebrew: "בפנים", partOfSpeech: "noun" },
  { id: 315, english: "install", hebrew: "להתקין", partOfSpeech: "verb" },
  { id: 316, english: "instead of", hebrew: "במקום", partOfSpeech: "preposition" },
  { id: 317, english: "instruction", hebrew: "הוראה, הנחיה", partOfSpeech: "noun" },
  { id: 318, english: "interesting", hebrew: "מעניין", partOfSpeech: "adjective" },
  { id: 319, english: "interior", hebrew: "פנימי", partOfSpeech: "adjective" },
  { id: 320, english: "interview", hebrew: "ראיון", partOfSpeech: "noun" },
  { id: 321, english: "introduction", hebrew: "הקדמה", partOfSpeech: "noun" },
  { id: 322, english: "invent", hebrew: "להמציא", partOfSpeech: "verb" },
  { id: 323, english: "invention", hebrew: "המצאה", partOfSpeech: "noun" },
  { id: 324, english: "inventor", hebrew: "ממציא", partOfSpeech: "noun" },
  { id: 325, english: "invitation", hebrew: "הזמנה", partOfSpeech: "noun" },
  { id: 326, english: "invite", hebrew: "להזמין", partOfSpeech: "verb" },
  { id: 327, english: "job", hebrew: "משרה, תפקיד", partOfSpeech: "noun" },
  { id: 328, english: "jump", hebrew: "לקפוץ", partOfSpeech: "verb" },
  { id: 329, english: "keep", hebrew: "לשמור", partOfSpeech: "verb" },
  { id: 330, english: "kilometer", hebrew: "קילומטר", partOfSpeech: "noun" },
  { id: 331, english: "kind", hebrew: "אדיב, סוג", partOfSpeech: "adjective, noun" },
  { id: 332, english: "kind of", hebrew: "סוג של", partOfSpeech: "idiom" },
  { id: 333, english: "know", hebrew: "לדעת", partOfSpeech: "verb" },
  { id: 334, english: "knowledge", hebrew: "ידע", partOfSpeech: "noun" },
  { id: 335, english: "lamp", hebrew: "מנורה", partOfSpeech: "noun" },
  { id: 336, english: "land", hebrew: "אדמה, לנחות", partOfSpeech: "verb, noun" },
  { id: 337, english: "language", hebrew: "שפה", partOfSpeech: "noun" },
  { id: 338, english: "last", hebrew: "אחרון, להימשך (זמן)", partOfSpeech: "verb, adjective" },
  { id: 339, english: "later", hebrew: "מאוחר יותר", partOfSpeech: "adverb" },
  { id: 340, english: "laugh", hebrew: "לצחוק", partOfSpeech: "verb" },
  { id: 341, english: "law", hebrew: "חוק", partOfSpeech: "noun" },
  { id: 342, english: "learn", hebrew: "ללמוד (לרכוש ידע)", partOfSpeech: "verb" },
  { id: 343, english: "leave", hebrew: "לעזוב, לצאת", partOfSpeech: "verb" },
  { id: 344, english: "less", hebrew: "פחות", partOfSpeech: "determiner" },
  { id: 345, english: "library", hebrew: "ספרייה", partOfSpeech: "noun" },
  { id: 346, english: "licence", hebrew: "רישיון", partOfSpeech: "noun" },
  { id: 347, english: "life", hebrew: "חיים", partOfSpeech: "noun" },
  { id: 348, english: "light", hebrew: "אור, קל (משקל), בהיר", partOfSpeech: "verb, noun, adjective" },
  { id: 349, english: "like", hebrew: "לאהוב, כמו", partOfSpeech: "verb" },
  { id: 350, english: "liquid", hebrew: "נוזל", partOfSpeech: "noun" },
  { id: 351, english: "listen", hebrew: "להקשיב", partOfSpeech: "verb" },
  { id: 352, english: "live", hebrew: "לחיות, לגור", partOfSpeech: "verb" },
  { id: 353, english: "load", hebrew: "עומס, לטעון", partOfSpeech: "verb, noun" },
  { id: 354, english: "log in", hebrew: "להתחבר", partOfSpeech: "verb" },
  { id: 355, english: "log out", hebrew: "להתנתק", partOfSpeech: "verb" },
  { id: 356, english: "look", hebrew: "להסתכל", partOfSpeech: "verb" },
  { id: 357, english: "look for", hebrew: "לחפש", partOfSpeech: "phrasal verb" },
  { id: 358, english: "loud", hebrew: "קולני", partOfSpeech: "adjective" },
  { id: 359, english: "love", hebrew: "אהבה, לאהוב", partOfSpeech: "verb" },
  { id: 360, english: "low", hebrew: "נמוך", partOfSpeech: "adjective" },
  { id: 361, english: "lunch", hebrew: "ארוחת צהריים", partOfSpeech: "noun" },
  { id: 362, english: "machine", hebrew: "מכונה", partOfSpeech: "noun" },
  { id: 363, english: "main", hebrew: "עיקרי", partOfSpeech: "adjective" },
  { id: 364, english: "major", hebrew: "עיקרי, ראשי", partOfSpeech: "adjective" },
  { id: 365, english: "make", hebrew: "לעשות, לייצר", partOfSpeech: "verb" },
  { id: 366, english: "make sure", hebrew: "לוודא", partOfSpeech: "idiom" },
  { id: 367, english: "manager", hebrew: "מנהל", partOfSpeech: "noun" },
  { id: 368, english: "manual", hebrew: "ידני, מדריך", partOfSpeech: "adjective" },
  { id: 369, english: "match", hebrew: "התאמה, להתאים", partOfSpeech: "noun, verb" },
  { id: 370, english: "material", hebrew: "חומר", partOfSpeech: "noun" },
  { id: 371, english: "meal", hebrew: "ארוחה", partOfSpeech: "noun" },
  { id: 372, english: "mean", hebrew: "להתכוון", partOfSpeech: "verb" },
  { id: 373, english: "meaning", hebrew: "משמעות", partOfSpeech: "noun" },
  { id: 374, english: "measure", hebrew: "למדוד, מידה", partOfSpeech: "verb, noun" },
  { id: 375, english: "mention", hebrew: "להזכיר", partOfSpeech: "verb" },
  { id: 376, english: "menu", hebrew: "תפריט", partOfSpeech: "noun" },
  { id: 377, english: "meter", hebrew: "מטר", partOfSpeech: "noun" },
  { id: 378, english: "method", hebrew: "שיטה", partOfSpeech: "noun" },
  { id: 379, english: "midnight", hebrew: "חצות", partOfSpeech: "noun" },
  { id: 380, english: "milimeter", hebrew: "מילימטר", partOfSpeech: "noun" },
  { id: 381, english: "minor", hebrew: "משני, קטן", partOfSpeech: "adjective" },
  { id: 382, english: "mix", hebrew: "לערבב", partOfSpeech: "verb" },
  { id: 383, english: "money", hebrew: "כסף", partOfSpeech: "noun" },
  { id: 384, english: "monitor", hebrew: "צג, לנטר", partOfSpeech: "noun, verb" },
  { id: 385, english: "month", hebrew: "חודש", partOfSpeech: "noun" },
  { id: 386, english: "more", hebrew: "יותר", partOfSpeech: "determiner" },
  { id: 387, english: "morning", hebrew: "בוקר", partOfSpeech: "noun" },
  { id: 388, english: "mother", hebrew: "אם, אמא", partOfSpeech: "noun" },
  { id: 389, english: "mountain", hebrew: "הר", partOfSpeech: "noun" },
  { id: 390, english: "move", hebrew: "לזוז, להזיז", partOfSpeech: "verb" },
  { id: 391, english: "movement", hebrew: "תנועה", partOfSpeech: "noun" },
  { id: 392, english: "movie", hebrew: "סרט", partOfSpeech: "noun" },
  { id: 393, english: "multiple", hebrew: "מרובה, רב", partOfSpeech: "adjective" },
  { id: 394, english: "must", hebrew: "חייב", partOfSpeech: "verb" },
  { id: 395, english: "narrow", hebrew: "צר", partOfSpeech: "adjective" },
  { id: 396, english: "near", hebrew: "קרוב", partOfSpeech: "adverb" },
  { id: 397, english: "necessary", hebrew: "הכרחי, נחוץ", partOfSpeech: "adjective" },
  { id: 398, english: "need", hebrew: "צורך, להזדקק", partOfSpeech: "verb, noun" },
  { id: 399, english: "negative", hebrew: "שלילי", partOfSpeech: "adjective" },
  { id: 400, english: "never", hebrew: "לעולם לא, אף פעם", partOfSpeech: "adverb" },
  { id: 401, english: "new", hebrew: "חדש", partOfSpeech: "adjective" },
  { id: 402, english: "newspaper", hebrew: "עיתון", partOfSpeech: "noun" },
  { id: 403, english: "next to", hebrew: "ליד", partOfSpeech: "preposition" },
  { id: 404, english: "nice", hebrew: "נחמד", partOfSpeech: "adjective" },
  { id: 405, english: "night", hebrew: "לילה", partOfSpeech: "noun" },
  { id: 406, english: "noise", hebrew: "רעש", partOfSpeech: "noun" },
  { id: 407, english: "noisy", hebrew: "רועש", partOfSpeech: "adjective" },
  { id: 408, english: "noon", hebrew: "צהריים", partOfSpeech: "noun" },
  { id: 409, english: "nothing", hebrew: "כלום, שום דבר", partOfSpeech: "pronoun" },
  { id: 410, english: "now", hebrew: "עכשיו", partOfSpeech: "adverb" },
  { id: 411, english: "nowadays", hebrew: "כיום", partOfSpeech: "adverb" },
  { id: 412, english: "number", hebrew: "מספר, למספר", partOfSpeech: "noun, verb" },
  { id: 413, english: "often", hebrew: "לעתים קרובות", partOfSpeech: "adverb" },
  { id: 414, english: "old", hebrew: "ישן, זקן", partOfSpeech: "adjective" },
  { id: 415, english: "on", hebrew: "על", partOfSpeech: "preposition" },
  { id: 416, english: "on the one hand", hebrew: "מצד אחד", partOfSpeech: "idiom" },
  { id: 417, english: "on the other hand", hebrew: "מצד שני", partOfSpeech: "idiom" },
  { id: 418, english: "open", hebrew: "פתוח, לפתוח", partOfSpeech: "adjective, verb" },
  { id: 419, english: "opinion", hebrew: "דעה", partOfSpeech: "noun" },
  { id: 420, english: "order", hebrew: "להזמין, סדר, הוראה", partOfSpeech: "verb, noun" },
  { id: 421, english: "organization", hebrew: "ארגון", partOfSpeech: "noun" },
  { id: 422, english: "organize", hebrew: "לארגן", partOfSpeech: "verb" },
  { id: 423, english: "outdoor", hebrew: "שבחוץ, באוויר הפתוח", partOfSpeech: "adjective" },
  { id: 424, english: "outside", hebrew: "בחוץ", partOfSpeech: "noun" },
  { id: 425, english: "over", hebrew: "מעל", partOfSpeech: "adverb" },
  { id: 426, english: "pain", hebrew: "כאב", partOfSpeech: "noun" },
  { id: 427, english: "painful", hebrew: "כואב", partOfSpeech: "adjective" },
  { id: 428, english: "paint", hebrew: "צבע, לצבוע", partOfSpeech: "verb, noun" },
  { id: 429, english: "paragraph", hebrew: "פסקה", partOfSpeech: "noun" },
  { id: 430, english: "parents", hebrew: "הורים", partOfSpeech: "noun" },
  { id: 431, english: "parking", hebrew: "חניה", partOfSpeech: "noun" },
  { id: 432, english: "participant", hebrew: "משתתף", partOfSpeech: "noun" },
  { id: 433, english: "participate", hebrew: "להשתתף", partOfSpeech: "verb" },
  { id: 434, english: "password", hebrew: "סיסמה", partOfSpeech: "noun" },
  { id: 435, english: "past", hebrew: "עבר", partOfSpeech: "noun" },
  { id: 436, english: "pay attention", hebrew: "לשים לב", partOfSpeech: "phrasal verb" },
  { id: 437, english: "peace", hebrew: "שלום", partOfSpeech: "noun" },
  { id: 438, english: "people", hebrew: "אנשים", partOfSpeech: "noun" },
  { id: 439, english: "percent", hebrew: "אחוז", partOfSpeech: "noun" },
  { id: 440, english: "permanent", hebrew: "קבוע", partOfSpeech: "adjective" },
  { id: 441, english: "person", hebrew: "אדם", partOfSpeech: "noun" },
  { id: 442, english: "personal", hebrew: "אישי", partOfSpeech: "adjective" },
  { id: 443, english: "phrase", hebrew: "ביטוי", partOfSpeech: "noun" },
  { id: 444, english: "picture", hebrew: "תמונה", partOfSpeech: "noun" },
  { id: 445, english: "piece", hebrew: "חתיכה, יחידה", partOfSpeech: "noun" },
  { id: 446, english: "place", hebrew: "מקום", partOfSpeech: "noun" },
  { id: 447, english: "play", hebrew: "לשחק, משחק", partOfSpeech: "verb, noun" },
  { id: 448, english: "plenty", hebrew: "שפע", partOfSpeech: "pronoun" },
  { id: 449, english: "plug", hebrew: "תקע, לחבר לחשמל", partOfSpeech: "verb, noun" },
  { id: 450, english: "pollute", hebrew: "לזהם", partOfSpeech: "verb" },
  { id: 451, english: "pollution", hebrew: "זיהום", partOfSpeech: "noun" },
  { id: 452, english: "pool", hebrew: "בריכה", partOfSpeech: "noun" },
  { id: 453, english: "poor", hebrew: "עני", partOfSpeech: "adjective" },
  { id: 454, english: "popular", hebrew: "פופולרי", partOfSpeech: "adjective" },
  { id: 455, english: "population", hebrew: "אוכלוסייה", partOfSpeech: "noun" },
  { id: 456, english: "positive", hebrew: "חיובי", partOfSpeech: "adjective" },
  { id: 457, english: "practice", hebrew: "תרגול, לתרגל", partOfSpeech: "verb, noun" },
  { id: 458, english: "prefer", hebrew: "להעדיף", partOfSpeech: "verb" },
  { id: 459, english: "prepare", hebrew: "להכין", partOfSpeech: "verb" },
  { id: 460, english: "present", hebrew: "מתנה, להציג, הווה", partOfSpeech: "noun, verb" },
  { id: 461, english: "presentation", hebrew: "מצגת", partOfSpeech: "noun" },
  { id: 462, english: "pressure", hebrew: "לחץ", partOfSpeech: "noun" },
  { id: 463, english: "prevent", hebrew: "למנוע", partOfSpeech: "verb" },
  { id: 464, english: "previous", hebrew: "קודם", partOfSpeech: "adjective" },
  { id: 465, english: "problem", hebrew: "בעיה", partOfSpeech: "noun" },
  { id: 466, english: "produce", hebrew: "לייצר", partOfSpeech: "verb" },
  { id: 467, english: "product", hebrew: "מוצר", partOfSpeech: "noun" },
  { id: 468, english: "production", hebrew: "ייצור", partOfSpeech: "noun" },
  { id: 469, english: "program", hebrew: "תוכנית", partOfSpeech: "noun" },
  { id: 470, english: "programer", hebrew: "מתכנת", partOfSpeech: "noun" },
  { id: 471, english: "project", hebrew: "פרויקט, מיזם", partOfSpeech: "noun" },
  { id: 472, english: "proof", hebrew: "הוכחה", partOfSpeech: "noun" },
  { id: 473, english: "protect", hebrew: "להגן", partOfSpeech: "verb" },
  { id: 474, english: "protein", hebrew: "חלבון", partOfSpeech: "noun" },
  { id: 475, english: "prove", hebrew: "להוכיח", partOfSpeech: "verb" },
  { id: 476, english: "provide", hebrew: "לספק", partOfSpeech: "verb" },
  { id: 477, english: "public", hebrew: "ציבורי", partOfSpeech: "adjective" },
  { id: 478, english: "pull", hebrew: "למשוך", partOfSpeech: "verb" },
  { id: 479, english: "purpose", hebrew: "תכלית, ייעוד", partOfSpeech: "noun" },
  { id: 480, english: "push", hebrew: "לדחוף", partOfSpeech: "verb" },
  { id: 481, english: "put", hebrew: "לשים", partOfSpeech: "verb" },
  { id: 482, english: "question", hebrew: "שאלה", partOfSpeech: "noun" },
  { id: 483, english: "quick", hebrew: "מהיר (זריז / זמן קצר)", partOfSpeech: "adjective" },
  { id: 484, english: "quickly", hebrew: "במהירות", partOfSpeech: "adverb" },
  { id: 485, english: "quiet", hebrew: "שקט", partOfSpeech: "adjective" },
  { id: 486, english: "reach", hebrew: "להגיע", partOfSpeech: "verb" },
  { id: 487, english: "read", hebrew: "לקרוא", partOfSpeech: "verb" },
  { id: 488, english: "reality", hebrew: "מציאות", partOfSpeech: "noun" },
  { id: 489, english: "reason", hebrew: "סיבה", partOfSpeech: "noun" },
  { id: 490, english: "recent", hebrew: "אחרון, לאחרונה", partOfSpeech: "adjective" },
  { id: 491, english: "recently", hebrew: "לאחרונה", partOfSpeech: "adverb" },
  { id: 492, english: "recommendation", hebrew: "המלצה", partOfSpeech: "noun" },
  { id: 493, english: "record", hebrew: "תיעוד, לרשום, שיא", partOfSpeech: "verb, noun" },
  { id: 494, english: "recycle", hebrew: "למחזר", partOfSpeech: "verb" },
  { id: 495, english: "recycling", hebrew: "מיחזור", partOfSpeech: "noun" },
  { id: 496, english: "reduce", hebrew: "להפחית", partOfSpeech: "verb" },
  { id: 497, english: "remain", hebrew: "להישאר", partOfSpeech: "verb" },
  { id: 498, english: "remember", hebrew: "לזכור", partOfSpeech: "verb" },
  { id: 499, english: "remember", hebrew: "לזכור", partOfSpeech: "verb" },
  { id: 500, english: "remote", hebrew: "מרוחק", partOfSpeech: "adjective" },
  { id: 501, english: "remote control", hebrew: "שלט רחוק", partOfSpeech: "noun" },
  { id: 502, english: "repeat", hebrew: "לחזור", partOfSpeech: "verb" },
  { id: 503, english: "replace", hebrew: "להחליף", partOfSpeech: "verb" },
  { id: 504, english: "report", hebrew: "דוח, לדווח", partOfSpeech: "noun, verb" },
  { id: 505, english: "reporter", hebrew: "כתב", partOfSpeech: "noun" },
  { id: 506, english: "research", hebrew: "מחקר", partOfSpeech: "noun" },
  { id: 507, english: "researcher", hebrew: "חוקר", partOfSpeech: "noun" },
  { id: 508, english: "resident", hebrew: "תושב", partOfSpeech: "noun" },
  { id: 509, english: "resource", hebrew: "משאב", partOfSpeech: "noun" },
  { id: 510, english: "responsibility", hebrew: "אחריות", partOfSpeech: "noun" },
  { id: 511, english: "responsible", hebrew: "אחראי", partOfSpeech: "adjective" },
  { id: 512, english: "restaurant", hebrew: "מסעדה", partOfSpeech: "noun" },
  { id: 513, english: "result", hebrew: "תוצאה", partOfSpeech: "noun, verb" },
  { id: 514, english: "rich", hebrew: "עשיר", partOfSpeech: "adjective" },
  { id: 515, english: "ride", hebrew: "לרכוב, נסיעה", partOfSpeech: "verb, noun" },
  { id: 516, english: "river", hebrew: "נהר", partOfSpeech: "noun" },
  { id: 517, english: "round", hebrew: "עגול", partOfSpeech: "adjective" },
  { id: 518, english: "route", hebrew: "מסלול", partOfSpeech: "noun" },
  { id: 519, english: "run", hebrew: "לרוץ, להריץ (תוכנה)", partOfSpeech: "verb" },
  { id: 520, english: "safe", hebrew: "בטוח, כספת", partOfSpeech: "noun, adjective" },
  { id: 521, english: "safety", hebrew: "בטיחות", partOfSpeech: "noun" },
  { id: 522, english: "salary", hebrew: "משכורת", partOfSpeech: "noun" },
  { id: 523, english: "same", hebrew: "אותו דבר", partOfSpeech: "adjective" },
  { id: 524, english: "save", hebrew: "לחסוך, להציל, לשמור (קובץ)", partOfSpeech: "verb" },
  { id: 525, english: "say", hebrew: "לומר", partOfSpeech: "verb" },
  { id: 526, english: "scared", hebrew: "מפוחד", partOfSpeech: "adjective" },
  { id: 527, english: "scary", hebrew: "מפחיד", partOfSpeech: "adjective" },
  { id: 528, english: "schedule", hebrew: "לוח זמנים", partOfSpeech: "noun" },
  { id: 529, english: "school", hebrew: "בית ספר", partOfSpeech: "noun" },
  { id: 530, english: "science", hebrew: "מדע", partOfSpeech: "noun" },
  { id: 531, english: "scientist", hebrew: "מדען", partOfSpeech: "noun" },
  { id: 532, english: "screen", hebrew: "מסך", partOfSpeech: "noun" },
  { id: 533, english: "sea", hebrew: "ים", partOfSpeech: "noun" },
  { id: 534, english: "search", hebrew: "חיפוש, לחפש", partOfSpeech: "verb" },
  { id: 535, english: "season", hebrew: "עונה, לתבל", partOfSpeech: "noun, verb" },
  { id: 536, english: "second", hebrew: "שני", partOfSpeech: "adjective" },
  { id: 537, english: "security", hebrew: "ביטחון", partOfSpeech: "noun" },
  { id: 538, english: "see", hebrew: "לראות", partOfSpeech: "verb" },
  { id: 539, english: "sensor", hebrew: "חיישן", partOfSpeech: "noun" },
  { id: 540, english: "sentence", hebrew: "משפט", partOfSpeech: "noun" },
  { id: 541, english: "server", hebrew: "שרת", partOfSpeech: "noun" },
  { id: 542, english: "several", hebrew: "מספר, כמה", partOfSpeech: "determiner" },
  { id: 543, english: "shop", hebrew: "חנות, לעשות קניות", partOfSpeech: "noun, verb" },
  { id: 544, english: "should", hebrew: "צריך", partOfSpeech: "verb" },
  { id: 545, english: "sick", hebrew: "חולה", partOfSpeech: "adjective" },
  { id: 546, english: "silent", hebrew: "שקט, דומם", partOfSpeech: "adjective" },
  { id: 547, english: "similar", hebrew: "דומה", partOfSpeech: "adjective" },
  { id: 548, english: "similarity", hebrew: "דמיון", partOfSpeech: "noun" },
  { id: 549, english: "sister", hebrew: "אחות", partOfSpeech: "noun" },
  { id: 550, english: "sit", hebrew: "לשבת", partOfSpeech: "verb" },
  { id: 551, english: "size", hebrew: "גודל", partOfSpeech: "noun" },
  { id: 552, english: "sleep", hebrew: "שינה, לישון", partOfSpeech: "verb, noun" },
  { id: 553, english: "slow", hebrew: "איטי", partOfSpeech: "adjective" },
  { id: 554, english: "small", hebrew: "קטן", partOfSpeech: "adjective" },
  { id: 555, english: "smile", hebrew: "חיוך, לחייך", partOfSpeech: "verb" },
  { id: 556, english: "smoke", hebrew: "עשן, לעשן", partOfSpeech: "verb, noun" },
  { id: 557, english: "so", hebrew: "כל כך, אז", partOfSpeech: "adverb" },
  { id: 558, english: "society", hebrew: "חברה", partOfSpeech: "noun" },
  { id: 559, english: "software", hebrew: "תוכנה", partOfSpeech: "noun" },
  { id: 560, english: "solar energy", hebrew: "אנרגיה סולרית", partOfSpeech: "noun" },
  { id: 561, english: "soldier", hebrew: "חייל", partOfSpeech: "noun" },
  { id: 562, english: "solution", hebrew: "פתרון", partOfSpeech: "noun" },
  { id: 563, english: "solve", hebrew: "לפתור", partOfSpeech: "verb" },
  { id: 564, english: "someone", hebrew: "מישהו", partOfSpeech: "pronoun" },
  { id: 565, english: "something", hebrew: "משהו", partOfSpeech: "pronoun" },
  { id: 566, english: "sometimes", hebrew: "לפעמים", partOfSpeech: "adverb" },
  { id: 567, english: "son", hebrew: "בן", partOfSpeech: "noun" },
  { id: 568, english: "soon", hebrew: "בקרוב", partOfSpeech: "adverb" },
  { id: 569, english: "source", hebrew: "מקור", partOfSpeech: "noun" },
  { id: 570, english: "special", hebrew: "מיוחד", partOfSpeech: "adjective" },
  { id: 571, english: "speed", hebrew: "מהירות", partOfSpeech: "noun, verb" },
  { id: 572, english: "spend money", hebrew: "להוציא כסף", partOfSpeech: "verb" },
  { id: 573, english: "spend time", hebrew: "לבלות זמן", partOfSpeech: "verb" },
  { id: 574, english: "spread", hebrew: "להתפשט, לפזר", partOfSpeech: "verb" },
  { id: 575, english: "spring", hebrew: "אביב, קפיץ, לזנק", partOfSpeech: "noun, verb" },
  { id: 576, english: "square", hebrew: "ריבוע, כיכר", partOfSpeech: "noun" },
  { id: 577, english: "stand", hebrew: "לעמוד", partOfSpeech: "verb" },
  { id: 578, english: "start", hebrew: "התחלה, להתחיל", partOfSpeech: "verb" },
  { id: 579, english: "status", hebrew: "מצב, סטטוס", partOfSpeech: "noun" },
  { id: 580, english: "stay", hebrew: "להישאר", partOfSpeech: "verb" },
  { id: 581, english: "store", hebrew: "חנות, לאחסן", partOfSpeech: "noun" },
  { id: 582, english: "strong", hebrew: "חזק", partOfSpeech: "adjective" },
  { id: 583, english: "study", hebrew: "ללמוד, לחקור", partOfSpeech: "verb, noun" },
  { id: 584, english: "subject", hebrew: "נושא, מקצוע (לימודים)", partOfSpeech: "noun" },
  { id: 585, english: "such as", hebrew: "כגון", partOfSpeech: "idiom" },
  { id: 586, english: "suggest", hebrew: "להציע", partOfSpeech: "verb" },
  { id: 587, english: "suitable", hebrew: "מתאים", partOfSpeech: "adjective" },
  { id: 588, english: "sum up", hebrew: "לסכם", partOfSpeech: "phrasal verb" },
  { id: 589, english: "summer", hebrew: "קיץ", partOfSpeech: "noun" },
  { id: 590, english: "sun", hebrew: "שמש", partOfSpeech: "noun" },
  { id: 591, english: "supper", hebrew: "ארוחת ערב", partOfSpeech: "noun" },
  { id: 592, english: "supplies", hebrew: "אספקה", partOfSpeech: "noun" },
  { id: 593, english: "supply", hebrew: "אספקה, לספק", partOfSpeech: "verb, noun" },
  { id: 594, english: "support", hebrew: "תמיכה, לתמוך", partOfSpeech: "verb, noun" },
  { id: 595, english: "survey", hebrew: "סקר", partOfSpeech: "noun" },
  { id: 596, english: "survive", hebrew: "לשרוד", partOfSpeech: "verb" },
  { id: 597, english: "swim", hebrew: "לשחות", partOfSpeech: "verb" },
  { id: 598, english: "system", hebrew: "מערכת", partOfSpeech: "noun" },
  { id: 599, english: "table", hebrew: "שולחן, טבלה", partOfSpeech: "noun" },
  { id: 600, english: "take", hebrew: "לקחת", partOfSpeech: "verb" },
  { id: 601, english: "take off", hebrew: "להמריא, להסיר", partOfSpeech: "phrasal verb" },
  { id: 602, english: "take part", hebrew: "לקחת חלק", partOfSpeech: "phrasal verb" },
  { id: 603, english: "talk", hebrew: "לדבר", partOfSpeech: "verb" },
  { id: 604, english: "target", hebrew: "מטרה (פיזית), יעד", partOfSpeech: "noun" },
  { id: 605, english: "tasty", hebrew: "טעים", partOfSpeech: "adjective" },
  { id: 606, english: "teach", hebrew: "ללמד", partOfSpeech: "verb" },
  { id: 607, english: "teacher", hebrew: "מורה", partOfSpeech: "noun" },
  { id: 608, english: "technology", hebrew: "טכנולוגיה", partOfSpeech: "noun" },
  { id: 609, english: "tell", hebrew: "לספר", partOfSpeech: "verb" },
  { id: 610, english: "temperature", hebrew: "טמפרטורה", partOfSpeech: "noun" },
  { id: 611, english: "thing", hebrew: "דבר", partOfSpeech: "noun" },
  { id: 612, english: "think", hebrew: "לחשוב", partOfSpeech: "verb" },
  { id: 613, english: "third", hebrew: "שלישי", partOfSpeech: "adjective" },
  { id: 614, english: "through", hebrew: "דרך, לאורך", partOfSpeech: "preposition" },
  { id: 615, english: "throw", hebrew: "לזרוק", partOfSpeech: "verb" },
  { id: 616, english: "tick", hebrew: "וי (סימן), לסמן", partOfSpeech: "verb, noun" },
  { id: 617, english: "tire", hebrew: "צמיג", partOfSpeech: "noun" },
  { id: 618, english: "title", hebrew: "כותרת", partOfSpeech: "noun" },
  { id: 619, english: "tool", hebrew: "כלי", partOfSpeech: "noun" },
  { id: 620, english: "topic", hebrew: "נושא, תחום", partOfSpeech: "noun" },
  { id: 621, english: "town", hebrew: "עיירה", partOfSpeech: "noun" },
  { id: 622, english: "toxic", hebrew: "רעיל", partOfSpeech: "adjective" },
  { id: 623, english: "train", hebrew: "רכבת, לאמן", partOfSpeech: "noun, verb" },
  { id: 624, english: "transfer", hebrew: "להעביר", partOfSpeech: "verb" },
  { id: 625, english: "translate", hebrew: "לתרגם", partOfSpeech: "verb" },
  { id: 626, english: "travel", hebrew: "לטייל, לנסוע", partOfSpeech: "verb" },
  { id: 627, english: "treat", hebrew: "לטפל, להתייחס", partOfSpeech: "verb" },
  { id: 628, english: "trip", hebrew: "טיול", partOfSpeech: "noun" },
  { id: 629, english: "trouble", hebrew: "צרה, טרדה", partOfSpeech: "noun" },
  { id: 630, english: "try", hebrew: "לנסות", partOfSpeech: "verb" },
  { id: 631, english: "turn", hebrew: "לפנות, לסובב, תור", partOfSpeech: "verb" },
  { id: 632, english: "turn off", hebrew: "לכבות", partOfSpeech: "phrasal verb" },
  { id: 633, english: "turn on", hebrew: "להדליק", partOfSpeech: "phrasal verb" },
  { id: 634, english: "type", hebrew: "סוג, להקליד", partOfSpeech: "verb, noun" },
  { id: 635, english: "unable", hebrew: "לא מסוגל", partOfSpeech: "adjective" },
  { id: 636, english: "uncle", hebrew: "דוד", partOfSpeech: "noun" },
  { id: 637, english: "under", hebrew: "מתחת", partOfSpeech: "adverb" },
  { id: 638, english: "underground", hebrew: "מתחת לאדמה", partOfSpeech: "noun" },
  { id: 639, english: "understand", hebrew: "להבין", partOfSpeech: "verb" },
  { id: 640, english: "unemployed", hebrew: "מובטל", partOfSpeech: "adjective" },
  { id: 641, english: "unemployment", hebrew: "אבטלה", partOfSpeech: "noun" },
  { id: 642, english: "university", hebrew: "אוניברסיטה", partOfSpeech: "noun" },
  { id: 643, english: "unlike", hebrew: "בניגוד ל-", partOfSpeech: "preposition" },
  { id: 644, english: "unnecessary", hebrew: "מיותר", partOfSpeech: "adjective" },
  { id: 645, english: "unusual", hebrew: "לא רגיל", partOfSpeech: "adjective" },
  { id: 646, english: "update", hebrew: "עדכון, לעדכן", partOfSpeech: "verb, noun" },
  { id: 647, english: "upload", hebrew: "להעלות (קובץ)", partOfSpeech: "verb" },
  { id: 648, english: "urgent", hebrew: "דחוף", partOfSpeech: "adjective" },
  { id: 649, english: "use", hebrew: "שימוש, להשתמש", partOfSpeech: "verb" },
  { id: 650, english: "user name", hebrew: "שם משתמש", partOfSpeech: "noun" },
  { id: 651, english: "usual", hebrew: "רגיל", partOfSpeech: "adjective" },
  { id: 652, english: "usually", hebrew: "בדרך כלל", partOfSpeech: "adverb" },
  { id: 653, english: "vehicle", hebrew: "רכב", partOfSpeech: "noun" },
  { id: 654, english: "version", hebrew: "גרסה", partOfSpeech: "noun" },
  { id: 655, english: "victim", hebrew: "קורבן", partOfSpeech: "noun" },
  { id: 656, english: "view", hebrew: "נוף, תצוגה", partOfSpeech: "noun" },
  { id: 657, english: "village", hebrew: "כפר", partOfSpeech: "noun" },
  { id: 658, english: "virtual reality", hebrew: "מציאות מדומה", partOfSpeech: "noun" },
  { id: 659, english: "visit", hebrew: "ביקור, לבקר", partOfSpeech: "verb, noun" },
  { id: 660, english: "visitor", hebrew: "מבקר", partOfSpeech: "noun" },
  { id: 661, english: "wait", hebrew: "לחכות", partOfSpeech: "verb" },
  { id: 662, english: "walk", hebrew: "ללכת", partOfSpeech: "verb" },
  { id: 663, english: "want", hebrew: "לרצות", partOfSpeech: "verb" },
  { id: 664, english: "warm", hebrew: "חם (מעט)", partOfSpeech: "adjective" },
  { id: 665, english: "wash", hebrew: "לרחוץ", partOfSpeech: "verb" },
  { id: 666, english: "washing machine", hebrew: "מכונת כביסה", partOfSpeech: "noun" },
  { id: 667, english: "waste money", hebrew: "לבזבז כסף", partOfSpeech: "phrasal verb" },
  { id: 668, english: "waste time", hebrew: "לבזבז זמן", partOfSpeech: "phrasal verb" },
  { id: 670, english: "water", hebrew: "מים", partOfSpeech: "noun" },
  { id: 669, english: "watch", hebrew: "שעון, לצפות", partOfSpeech: "verb, noun" },
  { id: 671, english: "weak", hebrew: "חלש", partOfSpeech: "adjective" },
  { id: 672, english: "week", hebrew: "שבוע", partOfSpeech: "noun" },
  { id: 673, english: "weigh", hebrew: "לשקול", partOfSpeech: "verb" },
  { id: 674, english: "weight", hebrew: "משקל", partOfSpeech: "noun" },
  { id: 675, english: "wet", hebrew: "רטוב", partOfSpeech: "adjective" },
  { id: 676, english: "what", hebrew: "מה", partOfSpeech: "interrogation" },
  { id: 677, english: "when", hebrew: "מתי", partOfSpeech: "interrogation" },
  { id: 678, english: "where", hebrew: "איפה", partOfSpeech: "interrogation" },
  { id: 679, english: "which", hebrew: "איזה", partOfSpeech: "interrogation" },
  { id: 680, english: "who", hebrew: "מי", partOfSpeech: "interrogation" },
  { id: 681, english: "why", hebrew: "למה", partOfSpeech: "interrogation" },
  { id: 682, english: "wide", hebrew: "רחב", partOfSpeech: "adjective" },
  { id: 683, english: "wife", hebrew: "אישה, אשה, בת זוג", partOfSpeech: "noun" },
  { id: 684, english: "wind", hebrew: "רוח", partOfSpeech: "noun" },
  { id: 685, english: "winter", hebrew: "חורף", partOfSpeech: "noun" },
  { id: 686, english: "word", hebrew: "מילה", partOfSpeech: "noun" },
  { id: 687, english: "work", hebrew: "עבודה (פעולה/מקום)", partOfSpeech: "noun" },
  { id: 688, english: "worker", hebrew: "עובד", partOfSpeech: "noun" },
  { id: 689, english: "workout", hebrew: "אימון", partOfSpeech: "verb, noun" },
  { id: 690, english: "workplace", hebrew: "מקום עבודה", partOfSpeech: "noun" },
  { id: 691, english: "world", hebrew: "עולם", partOfSpeech: "noun" },
  { id: 692, english: "world record", hebrew: "שיא עולמי", partOfSpeech: "noun" },
  { id: 693, english: "worldwide", hebrew: "עולמי", partOfSpeech: "adjective, adverb" },
  { id: 694, english: "write", hebrew: "לכתוב", partOfSpeech: "verb" },
  { id: 695, english: "writer", hebrew: "כותב, מחבר", partOfSpeech: "noun" },
  { id: 696, english: "year", hebrew: "שנה", partOfSpeech: "noun" },
  { id: 697, english: "young", hebrew: "צעיר", partOfSpeech: "adjective" },
  { id: 701, english: "calculate", hebrew: "לחשב", partOfSpeech: "verb" },
  { id: 702, english: "define", hebrew: "להגדיר", partOfSpeech: "verb" },
  { id: 703, english: "identify", hebrew: "לזהות", partOfSpeech: "verb" },
  { id: 704, english: "select", hebrew: "לבחור, לברור", partOfSpeech: "verb" },
  { id: 705, english: "refer to", hebrew: "להתייחס ל-", partOfSpeech: "phrasal verb" },
  { id: 706, english: "therefore", hebrew: "לכן", partOfSpeech: "adverb" },
  { id: 707, english: "despite", hebrew: "למרות", partOfSpeech: "preposition" },
  { id: 708, english: "various", hebrew: "מגוון, שונים", partOfSpeech: "adjective" },
  { id: 709, english: "global", hebrew: "גלובלי, עולמי", partOfSpeech: "adjective" },
  { id: 710, english: "available", hebrew: "זמין", partOfSpeech: "adjective" },
  { id: 711, english: "require", hebrew: "לדרוש, להצריך", partOfSpeech: "verb" },
  { id: 712, english: "process", hebrew: "תהליך", partOfSpeech: "noun" },
  { id: 713, english: "structure", hebrew: "מבנה", partOfSpeech: "noun" },
  { id: 714, english: "term", hebrew: "מונח", partOfSpeech: "noun" },
  { id: 715, english: "value", hebrew: "ערך", partOfSpeech: "noun" },
  { id: 716, english: "digital", hebrew: "דיגיטלי", partOfSpeech: "adjective" },
  { id: 717, english: "operation", hebrew: "פעולה, מבצע", partOfSpeech: "noun" },
  { id: 718, english: "simple", hebrew: "פשוט", partOfSpeech: "adjective" },
  { id: 719, english: "complex", hebrew: "מורכב, מסובך", partOfSpeech: "adjective" }
];
